import React, { useState } from "react";
import { View, Text, TouchableOpacity, StyleSheet } from "react-native";
import { GestureHandlerRootView } from "react-native-gesture-handler";
import { BottomSheetModalProvider } from "@gorhom/bottom-sheet";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Layout } from "~/src/ui/Layout";
import type { ToastProps } from "@shared/types";

const queryClient = new QueryClient();

const SUCCESS_MESSAGES = [
  "Record saved successfully!",
  "Changes have been applied.",
  "Upload completed.",
  "Profile updated.",
  "Payment processed successfully.",
  "Document submitted.",
];

const ERROR_MESSAGES = [
  "Something went wrong. Please try again.",
  "Network error. Check your connection.",
  "Failed to save changes.",
  "Upload failed. File too large.",
  "Session expired. Please log in again.",
  "Invalid data. Please check your inputs.",
];

const pick = (arr: string[]) => arr[Math.floor(Math.random() * arr.length)];

const SECTIONS = [
  {
    title: "Property Overview",
    body: "This section provides a comprehensive overview of all registered properties under the current jurisdiction. Each property record includes ownership details, transaction history, valuation data, and associated documents.",
  },
  {
    title: "Ownership Records",
    body: "Ownership records are maintained and updated in real-time. Any transfer of ownership triggers an audit trail that captures the previous owner, new owner, date of transfer, and the legal instrument used.",
  },
  {
    title: "Valuation & Assessment",
    body: "Properties are assessed annually based on market conditions, improvements, and comparative sales data. The valuation report is generated by a certified assessor and stored alongside the property record.",
  },
  {
    title: "Transaction History",
    body: "All financial transactions related to properties — including sales, mortgage registrations, and encumbrances — are logged here. Each entry is timestamped and linked to the responsible officer.",
  },
  {
    title: "Dispute Management",
    body: "Active and resolved disputes are tracked in this section. Dispute cases include boundary conflicts, ownership claims, and illegal occupancy reports. Each case has a status, assignee, and resolution notes.",
  },
  {
    title: "Document Archive",
    body: "Scanned and digital documents such as title deeds, NOCs, and survey maps are stored in a structured archive. Documents can be searched by property ID, owner name, or document type.",
  },
  {
    title: "Audit & Compliance",
    body: "The audit module tracks all user actions within the system, providing a full compliance trail. Scheduled audits and ad-hoc reviews are both supported with exportable reports.",
  },
  {
    title: "GIS Integration",
    body: "Property boundaries and parcel maps are integrated with the GIS layer. Users can visualize plots on an interactive map, draw boundaries, and cross-reference spatial data with registry records.",
  },
  {
    title: "Notifications & Alerts",
    body: "Automated notifications are sent for upcoming renewals, payment deadlines, and flagged irregularities. Users can configure their notification preferences per property or category.",
  },
  {
    title: "Reports & Analytics",
    body: "Generate detailed analytics on property distribution, ownership trends, transaction volumes, and revenue forecasts. Reports can be exported as PDF or Excel for stakeholder presentations.",
  },
];

export default function App() {
  const [toast, setToast] = useState<ToastProps>({
    message: "",
    status: "success",
  });

  const showToast = (status: "success" | "error") => {
    const message =
      status === "success" ? pick(SUCCESS_MESSAGES) : pick(ERROR_MESSAGES);
    setToast({ message, status });
    setTimeout(() => setToast({ message: "", status }), 3000);
  };

  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <QueryClientProvider client={queryClient}>
        <BottomSheetModalProvider>
          <Layout
            language="en"
            isEditing={false}
            showHeader
            showFooter
            bottomMargin={20}
            topMargin={50}
            toast={toast}
          >
            <View style={styles.container}>
              {/* Toast trigger buttons */}
              <View style={styles.buttonRow}>
                <TouchableOpacity
                  style={[styles.button, styles.successButton]}
                  onPress={() => showToast("success")}
                >
                  <Text style={styles.buttonText}>Show Success Toast</Text>
                </TouchableOpacity>
                <TouchableOpacity
                  style={[styles.button, styles.errorButton]}
                  onPress={() => showToast("error")}
                >
                  <Text style={styles.buttonText}>Show Error Toast</Text>
                </TouchableOpacity>
              </View>

              {/* Long scrollable content */}
              {SECTIONS.map((section, index) => (
                <View key={index} style={styles.section}>
                  <Text style={styles.sectionTitle}>{section.title}</Text>
                  <Text style={styles.sectionBody}>{section.body}</Text>
                  <View style={styles.placeholder} />
                </View>
              ))}
              {/* Toast trigger buttons */}
              <View style={styles.buttonRow}>
                <TouchableOpacity
                  style={[styles.button, styles.successButton]}
                  onPress={() => showToast("success")}
                >
                  <Text style={styles.buttonText}>Show Success Toast</Text>
                </TouchableOpacity>
                <TouchableOpacity
                  style={[styles.button, styles.errorButton]}
                  onPress={() => showToast("error")}
                >
                  <Text style={styles.buttonText}>Show Error Toast</Text>
                </TouchableOpacity>
              </View>
            </View>
          </Layout>
        </BottomSheetModalProvider>
      </QueryClientProvider>
    </GestureHandlerRootView>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 16,
    gap: 16,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 8,
  },
  button: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  successButton: {
    backgroundColor: "#16a34a",
  },
  errorButton: {
    backgroundColor: "#dc2626",
  },
  buttonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  section: {
    backgroundColor: "#f8f9fa",
    borderRadius: 10,
    padding: 16,
    gap: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1a202c",
  },
  sectionBody: {
    fontSize: 14,
    color: "#4a5568",
    lineHeight: 22,
  },
  placeholder: {
    height: 40,
    backgroundColor: "#e2e8f0",
    borderRadius: 6,
    marginTop: 4,
  },
});
