/* istanbul ignore file */
import type {
  ComponentConfig,
  IconType,
} from "@shared/types/dls.types";
import type { ApplicationTableProps } from "./Table";
import type { ComponentType } from "react";

const controls: ComponentConfig<ApplicationTableProps>["controls"] = {
  columns: {
    type: ["code"],
    label: "Columns",
    defaultValue: [
      { header: "Details", header_ar: "تفاصيل", accessorKey: "details" },
      { header: "Owner", header_ar: "المالك", accessorKey: "owner" },
      { header: "Plot", header_ar: "قطعة أرض", accessorKey: "plot" },
      { header: "Approval", header_ar: "الموافقة", accessorKey: "approval" },
      { header: "Payment", header_ar: "الدفع", accessorKey: "payment" },
      { header: "Print", header_ar: "طباعة", accessorKey: "print" },
    ],
    defaultCode: `return [
  { header: 'Details', header_ar: 'تفاصيل', accessorKey: 'details' },
  { header: 'Owner', header_ar: 'المالك', accessorKey: 'owner' },
  { header: 'Plot', header_ar: 'قطعة أرض', accessorKey: 'plot' },
  { header: 'Approval', header_ar: 'الموافقة', accessorKey: 'approval' },
  { header: 'Payment', header_ar: 'الدفع', accessorKey: 'payment' },
  { header: 'Print', header_ar: 'طباعة', accessorKey: 'print' },
]`,
  },
  data: {
    type: ["code"],
    label: "Data",
    defaultValue: [
      {
        applicationTitle: "New / Racing",
        applicationTitle_ar: "جديد / سباق",
        location: "Abu Dhabi City",
        location_ar: "مدينة أبوظبي",
        timeDate: "13:51 - 21/06/2025",
        daysRemaining: "X Days Remaining",
        id: "202500268615",
        currentStep: 3,
        additionalColumns: [
          {
            action: "Ahmed Mohammed 111",
            stepName: "Al Ketbi",
            userName: "Username",
            role: "Role",
            type: "success",
            version: "multi-row",
          },
          {
            action: "Ahmed Mohammed",
            stepName: "Al Ketbi",
            imageURL:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHSsMJwWbiNM-sWtPsfvq1mdV0rxJ-t7t-JQ&s",
            currentStep: 4,
            type: "action-other",
            version: "image-row",
          },
          {
            action: "Ahmed Mohammed",
            stepName: "Al Ketbi",
            currentStep: 4,
            type: "action",
            version: "single-row",
          },
          {
            action: "Pending",
            stepName: "Payment Pending",
            currentStep: 4,
            type: "pending",
            version: "hybrid",
            totalSteps: 6,
            currentStepStatus: "pending",
          },
          {
            action: "Pending",
            stepName: "Print Pending",
            currentStep: 4,
            type: "failed",
            version: "single-row",
            direction: "vertical",
          },
        ],
      },
      {
        applicationTitle: "New / Racing",
        applicationTitle_ar: "جديد / سباق",
        location: "Abu Dhabi City",
        location_ar: "مدينة أبوظبي",
        timeDate: "16:57 - 19/06/2025",
        timeDate_ar: "16:57 - 19/06/2025",
        daysRemaining: "X Days Remaining",
        id: "202500268102",
        currentStep: 1,
        additionalColumns: [
          {
            action: "Ahmed Mohammed 111",
            stepName: "Al Ketbi",
            userName: "Username",
            role: "Role",
            type: "success",
            version: "single-row",
          },
          {
            action: "Ahmed Mohammed",
            stepName: "Al Ketbi",
            imageURL:
              "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHSsMJwWbiNM-sWtPsfvq1mdV0rxJ-t7t-JQ&s",
            currentStep: 4,
            type: "action",
            version: "image-row",
          },
          {
            action: "Ahmed Mohammed",
            stepName: "Al Ketbi",
            userName: "Username",
            role: "Role",
            currentStep: 4,
            type: "action-other",
            version: "multi-row",
          },
          {
            action: "Pending",
            stepName: "Payment Pending",
            userName: "Username",
            role: "Role",
            currentStep: 4,
            type: "failed",
            version: "hybrid",
            totalSteps: 6,
            currentStepStatus: "failed",
          },
          {
            action: "Pending",
            stepName: "Print Pending",
            currentStep: 4,
            type: "pending",
            version: "single-row",
            direction: "vertical",
          },
        ],
      },
    ],
    defaultCode: `return [
          {
            applicationTitle: "New / Racing",
            applicationTitle_ar: "جديد / سباق",
            location: "Abu Dhabi City",
            location_ar: "مدينة أبوظبي",
            timeDate: "13:51 - 21/06/2025",
            daysRemaining: "X Days Remaining",
            id: "202500268615",
            currentStep: 3,
            additionalColumns: [
              {
                action: "Ahmed Mohammed 111",
                stepName: "Al Ketbi",
                userName: "Username",
                role: "Role",
                type: "success",
                version: "multi-row",
              },
              {
                action: "Ahmed Mohammed",
                stepName: "Al Ketbi",
                imageURL:
                  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHSsMJwWbiNM-sWtPsfvq1mdV0rxJ-t7t-JQ&s",
                currentStep: 4,
                type: "action-other",
                version: "image-row",
              },
              {
                action: "Ahmed Mohammed",
                stepName: "Al Ketbi",
                currentStep: 4,
                type: "action",
                version: "single-row",
              },
              {
                action: "Pending",
                stepName: "Payment Pending",
                currentStep: 4,
                type: "pending",
                version: "hybrid",
                totalSteps: 6,
                currentStepStatus: "pending",
              },
              {
                action: "Pending",
                stepName: "Print Pending",
                currentStep: 4,
                type: "failed",
                version: "single-row",
                direction: "vertical",
              },
            ],
          },
          {
            applicationTitle: "New / Racing",
            applicationTitle_ar: "جديد / سباق",
            location: "Abu Dhabi City",
            location_ar: "مدينة أبوظبي",
            timeDate: "16:57 - 19/06/2025",
            timeDate_ar: "16:57 - 19/06/2025",
            daysRemaining: "X Days Remaining",
            id: "202500268102",
            currentStep: 1,
            additionalColumns: [
              {
                action: "Ahmed Mohammed 111",
                stepName: "Al Ketbi",
                userName: "Username",
                role: "Role",
                type: "success",
                version: "single-row",
              },
              {
                action: "Ahmed Mohammed",
                stepName: "Al Ketbi",
                imageURL:
                  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHSsMJwWbiNM-sWtPsfvq1mdV0rxJ-t7t-JQ&s",
                currentStep: 4,
                type: "action",
                version: "image-row",
              },
              {
                action: "Ahmed Mohammed",
                stepName: "Al Ketbi",
                userName: "Username",
                role: "Role",
                currentStep: 4,
                type: "action-other",
                version: "multi-row",
              },
              {
                action: "Pending",
                stepName: "Payment Pending",
                userName: "Username",
                role: "Role",
                currentStep: 4,
                type: "failed",
                version: "hybrid",
                totalSteps: 6,
                currentStepStatus: "failed",
              },
              {
                action: "Pending",
                stepName: "Print Pending",
                currentStep: 4,
                type: "pending",
                version: "single-row",
                direction: "vertical",
              },
            ],
          },
        ]`,
  },
};

export function createTableConfig(
  Component: ComponentType<ApplicationTableProps>,
  icon: IconType
): ComponentConfig<ApplicationTableProps> {
  return {
    id: "table",
    icon,
    name: "Table",
    Component,
    controls,
  };
}
