/**
 * @adrec/mobile-ui-base Tailwind Preset
 *
 * This preset provides the theme colors used by the component library.
 * All CSS variables are resolved to actual hex values for React Native compatibility.
 *
 * Usage in your consumer app's tailwind.config.js:
 *
 * module.exports = {
 *   presets: [
 *     require('nativewind/preset'),
 *     require('@adrec/mobile-ui-base/tailwind.preset'),
 *   ],
 **/

/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        /* ==== Base ==== */
        "base-black": "#000000",
        "base-white": "#ffffff",
        "base-transparent": "transparent",

        /* ==== Set ==== */
        "set-primary": "#7d99a6",
        "set-secondary": "#008dcb",

        /* ==== Secondary scale ==== */
        "secondary-10": "#e5f4fa",
        "secondary-9": "#b3ddef",
        "secondary-8": "#80c6e5",
        "secondary-7": "#4cafdb",
        "secondary-6": "#1a98d0",
        "secondary-5": "#008dcb",
        "secondary-4": "#007fb7",
        "secondary-3": "#00638e",
        "secondary-2": "#004766",
        "secondary-1": "#002a3d",
        "secondary-0": "#000e14",

        /* ==== Primary Chrome scale ==== */
        "primary-chrome-light-saturated": "#f0f3f5",
        "primary-chrome-light": "#f9fbfc",
        "primary-chrome-18": "#f3f8fa",
        "primary-chrome-17": "#e6f2f5",
        "primary-chrome-16": "#d9e7ea",
        "primary-chrome-15": "#ccdce0",
        "primary-chrome-14": "#bfd1d5",
        "primary-chrome-13": "#b2c6cc",
        "primary-chrome-12": "#a5bbc2",
        "primary-chrome-11": "#97afb9",
        "primary-chrome-10": "#8aa4af",
        "primary-chrome-9": "#7d99a6",
        "primary-chrome-8": "#708a95",
        "primary-chrome-7": "#637b85",
        "primary-chrome-6": "#566c74",
        "primary-chrome-5": "#495d63",
        "primary-chrome-4": "#3c4e53",
        "primary-chrome-3": "#2f3f42",
        "primary-chrome-2": "#222f32",
        "primary-chrome-1": "#151f21",
        "primary-chrome-0": "#0a1010",
        "primary-chrome-faded": "#050808",

        /* ==== Blue scale ==== */
        "blue-saturated-20": "#5783db20",
        "blue-saturated": "#5783db",
        "blue-9": "#1864ab",
        "blue-8": "#1971c2",
        "blue-7": "#1c7ed6",
        "blue-6": "#228be6",
        "blue-5": "#339af0",
        "blue-4": "#4dabf7",
        "blue-3": "#74c0fc",
        "blue-2": "#a5d8ff",
        "blue-1": "#d0ebff",
        "blue-0": "#e7f5ff",

        /* ==== Red scale ==== */
        "red-9-20": "#ee3e4320",
        "red-9": "#ee3e43",
        "red-8": "#f05156",
        "red-7": "#f16569",
        "red-6": "#f3787b",
        "red-5": "#f58b8e",
        "red-4": "#f69ea1",
        "red-3": "#f8b2b4",
        "red-2": "#fac5c7",
        "red-1": "#fcd8d9",
        "red-0": "#fdecec",

        /* ==== Dark scale ==== */
        "dark-10": "#09090e",
        "dark-9": "#12121b",
        "dark-8": "#2a2a32",
        "dark-7": "#414149",
        "dark-6": "#59595f",
        "dark-5": "#717176",
        "dark-4": "#88888d",
        "dark-3": "#a0a0a4",
        "dark-2": "#b8b8bb",
        "dark-1": "#d0d0d1",
        "dark-0": "#e7e7e8",
        "dark-faded": "#f3f3f4",

        /* ==== Light scale ==== */
        "light-10": "#f8f8f9",
        "light-9": "#ebebec",
        "light-8": "#dedee0",
        "light-7": "#d1d1d3",
        "light-6": "#c4c4c7",
        "light-5": "#b7b7ba",
        "light-4": "#aaaaae",
        "light-3": "#9d9da1",
        "light-2": "#909095",
        "light-1": "#838388",
        "light-0": "#77777c",
        "light-faded": "#6a6a6f",

        /* ==== Green scale ==== */
        "green-9": "#2b8a3e",
        "green-8": "#2f9e44",
        "green-7": "#37b24d",
        "green-6": "#40c057",
        "green-5": "#51cf66",
        "green-4": "#69db7c",
        "green-3": "#8ce99a",
        "green-2": "#b2f2bb",
        "green-1": "#d3f9d8",
        "green-0": "#ebfbee",

        /* ==== Indigo scale ==== */
        "indigo-9": "#5d6edc",
        "indigo-8": "#7180e0",
        "indigo-7": "#8592e4",
        "indigo-6": "#99a5e8",
        "indigo-5": "#adb7ec",
        "indigo-4": "#c1c9f0",
        "indigo-3": "#d5dbf4",
        "indigo-2": "#e9edf8",
        "indigo-1": "#f3f5fb",
        "indigo-0": "#f2f3fb",
        "indigo-faded": "#fafafd",

        /* ==== Teal scale ==== */
        "teal-9": "#169f9f",
        "teal-8": "#2da9a9",
        "teal-7": "#45b2b2",
        "teal-6": "#5cbcbc",
        "teal-5": "#73c5c5",
        "teal-4": "#8acfcf",
        "teal-3": "#a2d9d9",
        "teal-2": "#b9e2e2",
        "teal-1": "#d0ecec",
        "teal-0": "#e8f5f5",
        "teal-faded": "#f3fafa",

        /* ==== Gold scale ==== */
        "gold-9": "#a38161",
        "gold-8": "#ac8e71",
        "gold-7": "#b59a81",
        "gold-6": "#bfa790",
        "gold-5": "#c8b3a0",
        "gold-4": "#d1c0b0",
        "gold-3": "#dacdc0",
        "gold-2": "#e3d9d0",
        "gold-1": "#ede6df",
        "gold-0": "#f6f2ef",
        "gold-faded": "#faf9f7",

        /* ==== Yellow scale ==== */
        "yellow-9": "#d0a621",
        "yellow-8": "#dcb023",
        "yellow-7": "#deb42f",
        "yellow-6": "#e2bd48",
        "yellow-5": "#e6c660",
        "yellow-4": "#eacf79",
        "yellow-3": "#edd791",
        "yellow-2": "#f1e0a9",
        "yellow-1": "#f5e9c2",
        "yellow-0": "#fbf6e6",

        /* ==== Form colors ==== */
        "form-back": "#f0f3f5",
        "form-border": "#e7e7e8",

        /* ==== Form Field colors ==== */
        "form-fields-active-input-text-active": "#050808",
        "form-fields-error": "#ee3e43",
        "form-fields-checkbox-radio-cbr-border": "#59595f",
        "form-fields-checkbox-radio-cbr-border-selected": "#008dcb",
        "form-fields-checkbox-radio-cb-icon": "#e7e7e8",
        "form-fields-checkbox-radio-cb-icon-selected": "#ffffff",
        "form-fields-checkbox-radio-cbr-bg": "#ffffff",
        "form-fields-checkbox-radio-cbr-bg-selected": "#008dcb",
        "form-fields-checkbox-radio-cbr-select-disable": "#ccdce0",
        "form-fields-disabled-input-bg-disabled": "#f0f3f5",
        "form-fields-disabled-input-border-disabled": "#e7e7e8",
        "form-fields-disabled-label-disabled": "#414149",
        "form-fields-disabled-icon-disabled": "#000000",
        "form-fields-input-form-bg": "#f0f3f5",
        "form-fields-input-form-border": "#e7e7e8",
        "form-fields-input-form-icon": "#000000",
        "form-fields-input-form-placeholder": "#a0a0a4",
        "form-fields-input-form-label": "#414149",
        "form-fields-captions-text-color": "#717176",
        "form-fields-label-text": "#414149",
        "form-fields-label-icon": "#a0a0a4",
        "form-fields-label-disabled": "#d0d0d1",
        "form-fields-file-upload-default": "#ebebec",
        "form-fields-file-upload-uploaded": "#f3f3f4",
        "form-fields-file-upload-uploaded-l1": "#f3f3f4",

        /* ==== Filter colors ==== */
        "filter-search-placeholder": "#a0a0a4",
        "filter-search-icon": "#a0a0a4",
        "filter-search-bg": "#f0f3f5",
        "filter-search-stroke": "#e7e7e8",
        "filter-search-selected-icon": "#12121b",
        "filter-search-selected-bg": "#ffffff",
        "filter-search-selected-stroke": "#7d99a6",
        "filter-button-text": "#59595f",
        "filter-button-bg-selected": "#f3f8fa",
        "filter-button-stroke-selected": "#ccdce0",
        "filter-button-badge": "#7d99a6",
        "filter-dropdown-bg": "#f8f8f9",

        /* ==== Cards colors ==== */
        "cards-base-l1": "#ffffff",
        "cards-base-l2": "#ffffff",
        "cards-stroke": "#e7e7e8",
        "cards-searchResult": "#ffffff",
        "cards-searchResult-selected": "#ffffff",
        "cards-process-card-text-light": "#ffffff",
        "cards-process-card-text-dark": "#000000",

        /* ==== Status colors ==== */
        "status-theme-light": "#8aa4af",
        "status-theme-solid": "#0a1010",
        "status-default-light": "#d1d1d3",
        "status-default-solid": "#59595f",
        "status-pending-light": "#e7f5ff",
        "status-pending-fade": "#d0ebff",
        "status-pending-solid": "#1864ab",
        "status-success-light": "#ebfbee",
        "status-success-fade": "#d3f9d8",
        "status-success-solid": "#2b8a3e",
        "status-failed-light": "#fdecec",
        "status-failed-fade": "#fcd8d9",
        "status-failed-solid": "#ee3e43",
        "status-action-light": "#fbf6e6",
        "status-action-fade": "#f5e9c2",
        "status-action-solid": "#d0a621",

        /* ==== Border colors ==== */
        "border-default": "#dedee0",
        "border-dimmed": "#c4c4c7",
        "border-light": "#ebebec",

        /* ==== Text colors ==== */
        "text-default": "#000000",
        "text-dimmed": "#9d9da1",
        "text-primary": "#7d99a6",
        "text-link": "#008dcb",
        "text-hover": "#4cafdb",

        /* ==== Button colors ==== */
        "button-primary-default-bg": "#008dcb",
        "button-primary-default-text": "#ffffff",
        "button-primary-hover": "#4cafdb",
        "button-primary-disabled": "#e7e7e8",
        "button-secondary-default-disabled-bg": "transparent",
        "button-secondary-default-text-stroke": "#008dcb",
        "button-secondary-hover-bg": "#e5f4fa",
        "button-secondary-disabled-stroke": "#a0a0a4",
        "button-tertiary-default-bg": "#12121b",
        "button-tertiary-default-text": "#ffffff",
        "button-tertiary-hover": "#414149",
        "button-tertiary-disabled-bg": "#59595f",
        "button-delete-stroke": "#ee3e43",
        "button-delete-hover-bg": "#fdecec",
        "button-radio-card-selected-disabled": "#e6f2f5",
        "button-radio-card-default": "#f3f8fa",

        /* ==== Structure colors ==== */
        "structure-primary-0": "#f3f8fa",
        "structure-primary-1": "#e6f2f5",
        "structure-primary-2": "#d9e7ea",
        "structure-primary-3": "#ccdce0",
        "structure-primary-4": "#bfd1d5",
        "structure-primary-5": "#b2c6cc",
        "structure-primary-6": "#a5bbc2",
        "structure-primary-7": "#97afb9",
        "structure-primary-8": "#8aa4af",
        "structure-primary-9": "#7d99a6",
        "structure-primary-9-dark": "#7d99a6",
        "structure-warning-light": "#fdecec",
        "structure-warning-mid-light": "#fcd8d9",
        "structure-main-background": "#f3f8fa",
        "structure-modal-level-1": "#f9fbfc",
        "structure-modal-level-2": "#f9fbfc",
        "structure-modal-level-3": "#f9fbfc",
        "structure-menu-background": "#f3f8fa",
        "structure-menu-text": "#717176",
        "structure-menu-icon": "#12121b",
        "structure-menu-select-background": "#ccdce0",
        "structure-menu-select-text": "#12121b",
        "structure-footer-background": "#ffffff",

        /* ==== Chart colors (HSL converted to hex) ==== */
        "chart-1": "#e87a5a",
        "chart-2": "#5cc9b5",
        "chart-3": "#3da4d9",
        "chart-4": "#b87fd9",
        "chart-5": "#e8a05a",

        /* ==== Semantic colors ==== */
        border: "#ebebe8",
        input: "#ebebe8",
        ring: "#b5b5b5",
        background: "#ffffff",
        foreground: "#161616",
        primary: {
          DEFAULT: "#1f1f1f",
          foreground: "#fafafa",
        },
        secondary: {
          DEFAULT: "#f5f5f5",
          foreground: "#1f1f1f",
        },
        destructive: {
          DEFAULT: "#ef4444",
          foreground: "#fafafa",
        },
        muted: {
          DEFAULT: "#f5f5f5",
          foreground: "#737373",
        },
        accent: {
          DEFAULT: "#f5f5f5",
          foreground: "#1f1f1f",
        },
        popover: {
          DEFAULT: "#ffffff",
          foreground: "#161616",
        },
        card: {
          DEFAULT: "#ffffff",
          foreground: "#161616",
        },
      },

      spacing: {
        none: "0px",
        xxs: "4px",
        xs: "8px",
        s: "12px",
        m: "16px",
        l: "24px",
        xl: "32px",
        xxl: "48px",
        xxxl: "64px",
      },

      padding: {
        none: "0px",
        xxs: "4px",
        xs: "8px",
        s: "12px",
        m: "16px",
        l: "24px",
        xl: "32px",
        xxl: "48px",
        xxxl: "64px",
      },

      borderRadius: {
        none: "0px",
        xxs: "4px",
        xs: "8px",
        s: "12px",
        m: "16px",
        l: "24px",
        xl: "32px",
        xxl: "48px",
        xxxl: "64px",
        full: "9999px",
      },

      opacity: {
        0: "0",
        10: "0.1",
        20: "0.2",
        30: "0.3",
        40: "0.4",
        50: "0.5",
        60: "0.6",
        70: "0.7",
        80: "0.8",
        90: "0.9",
      },

      fontSize: {
        xxs: ["10px", { lineHeight: "12px" }],
        xs: ["12px", { lineHeight: "16px" }],
        s: ["14px", { lineHeight: "18px" }],
        m: ["16px", { lineHeight: "20px" }],
        l: ["20px", { lineHeight: "24px" }],
        "heading-h1-shouting": ["80px", { lineHeight: "normal" }],
        "heading-h1-hero": ["64px", { lineHeight: "normal" }],
        "heading-h1": ["48px", { lineHeight: "56px" }],
        "heading-h2": ["32px", { lineHeight: "36px" }],
        "heading-h3": ["24px", { lineHeight: "28px" }],
        "heading-h4": ["16px", { lineHeight: "20px" }],
        10: "10px",
        12: "12px",
        14: "14px",
        16: "16px",
        18: "18px",
        20: "20px",
        24: "24px",
        32: "32px",
        48: "48px",
      },

      boxShadow: {
        "modal-light": "0px 24px 48px 12px rgba(0, 0, 0, 0.15)",
        "modal-dark": "0px 24px 32px 12px rgba(0, 0, 0, 0.25)",
      },
    },
  },
};
